location:
    raw_today_data: '/home/vasanth/airflow/scripts/mlproject/data/raw/today_data.csv'
    today_data : '/home/vasanth/airflow/scripts/mlproject/data/processed/today_data.csv'
    raw_yesterday_data : '/home/vasanth/airflow/scripts/mlproject/data/raw/yesterday_data.csv'
    yesterday_data : '/home/vasanth/airflow/scripts/mlproject/data/processed/yesterday_data.csv'
    tracking_uri : 'file:////home/vasanth/airflow/scripts/mlproject/src/models/mlruns'
    registry_uri : 'postgresql://postgres:postgres@localhost/mlflow'
    today_data_predictions: '/home/vasanth/airflow/scripts/mlproject/data/predictions/today_predictions.csv'
    yesterday_data_predictions : '/home/vasanth/airflow/scripts/mlproject/data/predictions/yesterday_data_results.csv'
    trained_model_predictions : '/home/vasanth/airflow/scripts/mlproject/data/predictions/trained_data_results.csv'
    mlflow_artifacts : '/home/vasanth/airflow/scripts/mlproject/src/models'
    data_drift : '/home/vasanth/airflow/scripts/mlproject/src/visualization/data_drift.html'
    model_drift : '/home/vasanth/airflow/scripts/mlproject/src/visualization/regression_drift.html'
experiment_details:
    name : 'random_forest_3'
model_parameters:
   target : quality
   problem_type : 'regression'
   model_type : RandomForestRegressor
   parameters :  {'max_depth' : [1,2], 'n_estimators' : [10,500,1000], 'max_features': [1,2]}
